service: selector

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  profile: selector

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  patterns:
    - '!./**'
    - './bin/**'

functions:
  selector:
    handler: bin/main
    events:
      - http: 'POST /'
    # url: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useDocker: true
